# Generated by Django 3.0.6 on 2020-05-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='bed_number',
            field=models.IntegerField(),
        ),
    ]
