# Generated by Django 3.0.6 on 2020-05-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nid_no',
            field=models.CharField(max_length=32, verbose_name='NID No'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.CharField(max_length=13, verbose_name='Phone No'),
        ),
    ]
